### PR TITLE
updated sonar-example project for combined ut-it coverage project

### PR DESCRIPTION
**Pull request by lkwg82**
this is my suggestion, maybe you update requirement of maven 2.2.1 to maven 3?

Cheers Lars

### CODE REVIEW

**Comment by benzonico** [comment]
Thanks a lot for your contribution ! 
I merged it manually with https://github.com/SonarSource/sonar-examples/commit/6797f460a730dfbe801849d6adecd83b36527c7c 

Cheers!

**Comment by Godin** [comment]
@benzonico I hope that you didn't changed source version for javac as in this proposition? ;)

**Comment by lkwg82** [comment]
@Godin 

If java 1.5 compatibility is an issue, please test with the specific jdks as well.

I did not!

Cheers Lars

**Comment by benzonico** [comment]
@Godin You can (and I bet you already did ;)) check there : https://github.com/SonarSource/sonar-examples/commit/6797f460a730dfbe801849d6adecd83b36527c7c No update of source compatibility.

@lkwg82 : @Godin was talking about that : https://github.com/lkwg82/sonar-examples/commit/f6c62002d3a6aa3695ac8159d8aee6853fdb985f#diff-9ab8d2bf7a4d41686ba28c53a0829632R45 Might have worth mentioning that I corrected this while merging.

**Pull request closed without merging**
